-- File: onboarding-server/schemas/tables/countries.sql

DROP TABLE IF EXISTS countries; 

CREATE TABLE IF NOT EXISTS countries (
    country_code CHAR(2) NOT NULL COMMENT 'ISO 3166-1 alpha-2 code',
    locale_code VARCHAR(10) NOT NULL COMMENT 'e.g., en_US, en_AU',
    locale_name VARCHAR(100) NOT NULL COMMENT 'Country name in the specified locale',

    PRIMARY KEY (country_code, locale_code), 
    UNIQUE KEY uni_locale (locale_code, locale_name) 

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores country codes and localized names';

INSERT IGNORE INTO countries (country_code, locale_code, locale_name) VALUES
-- Asia
('AF', 'fa_AF', 'Afghanistan'),
('AM', 'hy_AM', 'Armenia'),
('AZ', 'az_AZ', 'Azerbaijan'),
('BH', 'ar_BH', 'Bahrain'),
('BD', 'bn_BD', 'Bangladesh'),
('BT', 'dz_BT', 'Bhutan'),
('BN', 'ms_BN', 'Brunei'),
('KH', 'km_KH', 'Cambodia'),
('CN', 'zh_CN', 'China'),
('GE', 'ka_GE', 'Georgia'),
('IN', 'hi_IN', 'India'),
('ID', 'id_ID', 'Indonesia'),
('IR', 'fa_IR', 'Iran'),
('IQ', 'ar_IQ', 'Iraq'),
('IL', 'he_IL', 'Israel'),
('JP', 'ja_JP', 'Japan'),
('JO', 'ar_JO', 'Jordan'),
('KZ', 'kk_KZ', 'Kazakhstan'),
('KW', 'ar_KW', 'Kuwait'),
('KG', 'ky_KG', 'Kyrgyzstan'),
('LA', 'lo_LA', 'Laos'),
('LB', 'ar_LB', 'Lebanon'),
('MY', 'ms_MY', 'Malaysia'),
('MV', 'dv_MV', 'Maldives'),
('MN', 'mn_MN', 'Mongolia'),
('MM', 'my_MM', 'Myanmar'),
('NP', 'ne_NP', 'Nepal'),
('KP', 'ko_KP', 'North Korea'),
('OM', 'ar_OM', 'Oman'),
('PK', 'ur_PK', 'Pakistan'),
('PS', 'ar_PS', 'Palestine'),
('PH', 'en_PH', 'Philippines'),
('QA', 'ar_QA', 'Qatar'),
('SA', 'ar_SA', 'Saudi Arabia'),
('SG', 'en_SG', 'Singapore'),
('KR', 'ko_KR', 'South Korea'),
('LK', 'si_LK', 'Sri Lanka'),
('SY', 'ar_SY', 'Syria'),
('TW', 'zh_TW', 'Taiwan'),
('TJ', 'tg_TJ', 'Tajikistan'),
('TH', 'th_TH', 'Thailand'),
('TL', 'pt_TL', 'Timor-Leste'),
('TR', 'tr_TR', 'Turkey'),
('TM', 'tk_TM', 'Turkmenistan'),
('AE', 'ar_AE', 'United Arab Emirates'),
('UZ', 'uz_UZ', 'Uzbekistan'),
('VN', 'vi_VN', 'Vietnam'),
('YE', 'ar_YE', 'Yemen'),

-- Europe
('AL', 'sq_AL', 'Albania'),
('AD', 'ca_AD', 'Andorra'),
('AT', 'de_AT', 'Austria'),
('BY', 'be_BY', 'Belarus'),
('BE', 'nl_BE', 'Belgium'),
('BA', 'bs_BA', 'Bosnia and Herzegovina'),
('BG', 'bg_BG', 'Bulgaria'),
('HR', 'hr_HR', 'Croatia'),
('CY', 'el_CY', 'Cyprus'),
('CZ', 'cs_CZ', 'Czech Republic'),
('DK', 'da_DK', 'Denmark'),
('EE', 'et_EE', 'Estonia'),
('FI', 'fi_FI', 'Finland'),
('FR', 'fr_FR', 'France'),
('DE', 'de_DE', 'Germany'),
('GR', 'el_GR', 'Greece'),
('HU', 'hu_HU', 'Hungary'),
('IS', 'is_IS', 'Iceland'),
('IE', 'en_IE', 'Ireland'),
('IT', 'it_IT', 'Italy'),
('XK', 'sq_XK', 'Kosovo'),
('LV', 'lv_LV', 'Latvia'),
('LI', 'de_LI', 'Liechtenstein'),
('LT', 'lt_LT', 'Lithuania'),
('LU', 'lb_LU', 'Luxembourg'),
('MT', 'mt_MT', 'Malta'),
('MD', 'ro_MD', 'Moldova'),
('MC', 'fr_MC', 'Monaco'),
('ME', 'sr_ME', 'Montenegro'),
('NL', 'nl_NL', 'Netherlands'),
('MK', 'mk_MK', 'North Macedonia'),
('NO', 'no_NO', 'Norway'),
('PL', 'pl_PL', 'Poland'),
('PT', 'pt_PT', 'Portugal'),
('RO', 'ro_RO', 'Romania'),
('RU', 'ru_RU', 'Russia'),
('SM', 'it_SM', 'San Marino'),
('RS', 'sr_RS', 'Serbia'),
('SK', 'sk_SK', 'Slovakia'),
('SI', 'sl_SI', 'Slovenia'),
('ES', 'es_ES', 'Spain'),
('SE', 'sv_SE', 'Sweden'),
('CH', 'de_CH', 'Switzerland'),
('UA', 'uk_UA', 'Ukraine'),
('GB', 'en_GB', 'United Kingdom'),
('VA', 'it_VA', 'Vatican City'),

-- Africa
('DZ', 'ar_DZ', 'Algeria'),
('AO', 'pt_AO', 'Angola'),
('BJ', 'fr_BJ', 'Benin'),
('BW', 'en_BW', 'Botswana'),
('BF', 'fr_BF', 'Burkina Faso'),
('BI', 'fr_BI', 'Burundi'),
('CM', 'fr_CM', 'Cameroon'),
('CV', 'pt_CV', 'Cape Verde'),
('CF', 'fr_CF', 'Central African Republic'),
('TD', 'fr_TD', 'Chad'),
('KM', 'ar_KM', 'Comoros'),
('CG', 'fr_CG', 'Congo'),
('CD', 'fr_CD', 'Democratic Republic of the Congo'),
('CI', 'fr_CI', 'Ivory Coast'),
('DJ', 'fr_DJ', 'Djibouti'),
('EG', 'ar_EG', 'Egypt'),
('GQ', 'es_GQ', 'Equatorial Guinea'),
('ER', 'ti_ER', 'Eritrea'),
('SZ', 'en_SZ', 'Eswatini'),
('ET', 'am_ET', 'Ethiopia'),
('GA', 'fr_GA', 'Gabon'),
('GM', 'en_GM', 'Gambia'),
('GH', 'en_GH', 'Ghana'),
('GN', 'fr_GN', 'Guinea'),
('GW', 'pt_GW', 'Guinea-Bissau'),
('KE', 'sw_KE', 'Kenya'),
('LS', 'en_LS', 'Lesotho'),
('LR', 'en_LR', 'Liberia'),
('LY', 'ar_LY', 'Libya'),
('MG', 'mg_MG', 'Madagascar'),
('MW', 'en_MW', 'Malawi'),
('ML', 'fr_ML', 'Mali'),
('MR', 'ar_MR', 'Mauritania'),
('MU', 'en_MU', 'Mauritius'),
('MA', 'ar_MA', 'Morocco'),
('MZ', 'pt_MZ', 'Mozambique'),
('NA', 'en_NA', 'Namibia'),
('NE', 'fr_NE', 'Niger'),
('NG', 'en_NG', 'Nigeria'),
('RW', 'rw_RW', 'Rwanda'),
('ST', 'pt_ST', 'São Tomé and Príncipe'),
('SN', 'fr_SN', 'Senegal'),
('SC', 'en_SC', 'Seychelles'),
('SL', 'en_SL', 'Sierra Leone'),
('SO', 'so_SO', 'Somalia'),
('ZA', 'en_ZA', 'South Africa'),
('SS', 'en_SS', 'South Sudan'),
('SD', 'ar_SD', 'Sudan'),
('TZ', 'sw_TZ', 'Tanzania'),
('TG', 'fr_TG', 'Togo'),
('TN', 'ar_TN', 'Tunisia'),
('UG', 'en_UG', 'Uganda'),
('ZM', 'en_ZM', 'Zambia'),
('ZW', 'en_ZW', 'Zimbabwe'),

-- North America
('AG', 'en_AG', 'Antigua and Barbuda'),
('BS', 'en_BS', 'Bahamas'),
('BB', 'en_BB', 'Barbados'),
('BZ', 'en_BZ', 'Belize'),
('CA', 'en_CA', 'Canada'),
('CR', 'es_CR', 'Costa Rica'),
('CU', 'es_CU', 'Cuba'),
('DM', 'en_DM', 'Dominica'),
('DO', 'es_DO', 'Dominican Republic'),
('SV', 'es_SV', 'El Salvador'),
('GD', 'en_GD', 'Grenada'),
('GT', 'es_GT', 'Guatemala'),
('HT', 'fr_HT', 'Haiti'),
('HN', 'es_HN', 'Honduras'),
('JM', 'en_JM', 'Jamaica'),
('MX', 'es_MX', 'Mexico'),
('NI', 'es_NI', 'Nicaragua'),
('PA', 'es_PA', 'Panama'),
('KN', 'en_KN', 'Saint Kitts and Nevis'),
('LC', 'en_LC', 'Saint Lucia'),
('VC', 'en_VC', 'Saint Vincent and the Grenadines'),
('TT', 'en_TT', 'Trinidad and Tobago'),
('US', 'en_US', 'United States'),

-- South America
('AR', 'es_AR', 'Argentina'),
('BO', 'es_BO', 'Bolivia'),
('BR', 'pt_BR', 'Brazil'),
('CL', 'es_CL', 'Chile'),
('CO', 'es_CO', 'Colombia'),
('EC', 'es_EC', 'Ecuador'),
('GY', 'en_GY', 'Guyana'),
('PY', 'es_PY', 'Paraguay'),
('PE', 'es_PE', 'Peru'),
('SR', 'nl_SR', 'Suriname'),
('UY', 'es_UY', 'Uruguay'),
('VE', 'es_VE', 'Venezuela'),

-- Australia - Oceania
('AU', 'en_AU', 'Australia'),
('FJ', 'en_FJ', 'Fiji'),
('KI', 'en_KI', 'Kiribati'),
('MH', 'en_MH', 'Marshall Islands'),
('FM', 'en_FM', 'Micronesia'),
('NR', 'en_NR', 'Nauru'),
('NZ', 'en_NZ', 'New Zealand'),
('PW', 'en_PW', 'Palau'),
('PG', 'en_PG', 'Papua New Guinea'),
('WS', 'sm_WS', 'Samoa'),
('SB', 'en_SB', 'Solomon Islands'),
('TO', 'to_TO', 'Tonga'),
('TV', 'en_TV', 'Tuvalu'),
('VU', 'bi_VU', 'Vanuatu');